/*
 * MODT (Modeling Tool)
 * Copyright (C) 2026 Eduard Fekete <modt@eduardfekete.com>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

#include "DocGenerator.hpp"
#include <sstream>
#include <format>
#include <ranges>

namespace Generator {

std::string DocGenerator::generate(const Model::Project& project) {
    std::stringstream ss;
    ss << "<!-- Documentation generated by MODT -->\n";
    ss << std::format("# Project Documentation: {}\n\n", project.title.empty() ? project.name : project.title);

    if (!project.description.empty()) {
        ss << project.description << "\n\n";
    }

    if (!project.useCases.empty()) {
        ss << "## Use Cases\n\n";
        for (const auto& uc : project.useCases) {
            ss << std::format("### {}\n", uc.name);
            if (!uc.description.empty()) ss << std::format("**Description:** {}\n\n", uc.description);
            if (!uc.actor.empty()) ss << std::format("**Actor:** {}\n\n", translateStereotype(uc.actor));
            
            if (!uc.preconditions.empty()) {
                ss << "**Preconditions:**\n";
                for (const auto& pre : uc.preconditions) {
                    if (pre.find('.') != std::string::npos || pre[0] == '#' || pre[0] == '!') {
                        ss << std::format("- `{}`\n", pre);
                    } else {
                        ss << std::format("- {}\n", pre);
                    }
                }
                ss << "\n";
            }

            ss << "**Flow of Events:**\n";
            int stepNum = 1;
            for (const auto& action : uc.actions) {
                std::string prefix = "";
                if (action.isAlternative) {
                    prefix += action.condition.empty() ? "[Alt] " : std::format("[Alt: {}] ", action.condition);
                } else if (!action.condition.empty()) {
                    prefix += std::format("[{}] ", action.condition);
                }
                
                if (!action.gotoLabel.empty()) {
                    ss << std::format("{}. {}**Repeat** step labeled {}\n", stepNum++, prefix, action.gotoLabel);
                } else {
                    ss << std::format("{}. {}{} ", stepNum++, prefix, action.name);
                    if (!action.target.empty()) {
                        std::string targetLabel = translateStereotype(action.target);
                        if (targetLabel != "system") ss << std::format("(Target: {})", targetLabel);
                    }
                    ss << "\n";
                    for (const auto& param : action.parameters) {
                        ss << std::format("    - {}{}\n", param.name, (param.type.empty() ? "" : ": " + param.type));
                    }
                }
            }
            ss << "\n";

            if (!uc.postconditions.empty()) {
                ss << "**Postconditions:**\n";
                for (const auto& post : uc.postconditions) {
                    if (post.find('.') != std::string::npos || post[0] == '#' || post[0] == '!') {
                        ss << std::format("- `{}`\n", post);
                    } else {
                        ss << std::format("- {}\n", post);
                    }
                }
                ss << "\n";
            }
        }
    }

    if (!project.classes.empty()) {
        ss << "## Domain Model\n\n";
        for (const auto& cls : project.classes) {
            ss << std::format("### Class: {}\n", cls.name);
            if (cls.isAnalysis && !cls.isDesign) ss << "*Phase: Analysis*\n\n";
            else if (!cls.isAnalysis && cls.isDesign) ss << "*Phase: Design*\n\n";

            if (!cls.baseClass.empty()) ss << std::format("**Inherits from:** {}\n\n", cls.baseClass);

            if (!cls.stereotypes.empty()) {
                ss << "**Stereotypes:** ";
                for (const auto& s : cls.stereotypes) ss << std::format("`<<{}>>` ", translateStereotype(s));
                ss << "\n\n";
            }
            
            if (!cls.attributes.empty()) {
                ss << "#### Attributes\n\n";
                ss << "| Attribute | Type | Visibility | Metadata |\n";
                ss << "| --- | --- | --- | --- |\n";
                for (const auto& attr : cls.attributes) {
                    ss << std::format("| {} | {} | {} | ", 
                        attr.name, 
                        (attr.type.empty() ? "-" : attr.type), 
                        (attr.visibility.empty() ? "unspecified" : attr.visibility));
                    
                    if (!attr.metadata.empty()) {
                        for (auto it = attr.metadata.begin(); it != attr.metadata.end(); ++it) {
                            ss << std::format("`{}", it->first);
                            if (!it->second.empty()) ss << std::format("({})", it->second);
                            ss << std::format("`{}", (std::next(it) == attr.metadata.end() ? "" : ", "));
                        }
                    } else {
                        ss << "-";
                    }
                    ss << " |\n";
                }
                ss << "\n";
            }

            if (!cls.methods.empty()) {
                ss << "#### Methods\n\n";
                ss << "| Method | Visibility | Effects | Pre/Post Conditions |\n";
                ss << "| --- | --- | --- | --- |\n";
                for (const auto& method : cls.methods) {
                    std::string sig = method.name + "(";
                    for (size_t i = 0; i < method.parameters.size(); ++i) {
                        sig += method.parameters[i].name;
                        if (!method.parameters[i].type.empty()) sig += ": " + method.parameters[i].type;
                        if (i < method.parameters.size() - 1) sig += ", ";
                    }
                    sig += ")";
                    
                    ss << std::format("| {} | {} | ", 
                        sig, 
                        (method.visibility.empty() ? "unspecified" : method.visibility));
                    
                    std::string effects = "";
                    for (const auto& eff : method.effects) {
                        std::string from = eff.fromValue.empty() ? "" : (std::format("({}) ", eff.fromValue));
                        effects += std::format("`{}`: {}{} -> {}", 
                            (eff.trigger.empty() ? "Always" : eff.trigger), 
                            from, eff.variable, eff.value);
                        if (&eff != &method.effects.back()) effects += "<br>";
                    }
                    ss << (effects.empty() ? "-" : effects) << " | ";

                    std::string conds = "";
                    for (const auto& pre : method.preconditions) {
                        std::string p = pre;
                        for (const auto& attr : cls.attributes) {
                            if (attr.metadata.contains("state") && p.find(attr.name) == std::string::npos && p.find("_") != std::string::npos) {
                                p = attr.name + " == " + p;
                            }
                        }
                        conds += "**pre** " + p + "<br>";
                    }
                    for (const auto& post : method.postconditions) {
                        std::string p = post;
                        for (const auto& attr : cls.attributes) {
                            if (attr.metadata.contains("state") && p.find(attr.name) == std::string::npos && p.find("_") != std::string::npos) {
                                p = attr.name + " := " + p;
                            }
                        }
                        conds += "**post** " + p + "<br>";
                    }
                    ss << (conds.empty() ? "-" : conds) << " |\n";
                }
                ss << "\n";
            }
        }
    }

    if (!project.enums.empty()) {
        ss << "## Enumerations\n\n";
        for (const auto& en : project.enums) {
            ss << std::format("### Enum: {}\n", en.name);
            if (en.isAnalysis && !en.isDesign) ss << "*Phase: Analysis*\n\n";
            else if (!en.isAnalysis && en.isDesign) ss << "*Phase: Design*\n\n";

            ss << "**Values:**\n";
            for (const auto& v : en.values) {
                ss << std::format("- `{}`\n", v);
            }
            ss << "\n";
        }
    }

    if (!project.relationships.empty()) {
        ss << "## Relationships\n\n";
        ss << "| From | Type | To | Label |\n";
        ss << "| --- | --- | --- | --- |\n";
        for (const auto& rel : project.relationships) {
            ss << std::format("| {} {} | {} | {} {} | {} |\n", 
                rel.from, (rel.fromLabel.empty() ? "" : std::format("\"{}\"", rel.fromLabel)),
                rel.type,
                (rel.toLabel.empty() ? "" : std::format("\"{}\"", rel.toLabel)), rel.to,
                rel.label);
        }
        ss << "\n";
    }

    return ss.str();
}

std::string DocGenerator::translateStereotype(const std::string& s) {
    if (s == "@sys") return "system";
    if (s == "@user") return "User";
    if (s == "@ext") return "External Service";
    if (s == "@db") return "Database";
    if (s == "@api") return "External API";
    if (!s.empty() && s[0] == '@') return s.substr(1);
    return s;
}

} // namespace Generator
