/*
 * MODT (Modeling Tool)
 * Copyright (C) 2026 Eduard Fekete <modt@eduardfekete.com>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

#include "PumlGenerator.hpp"
#include <sstream>
#include <algorithm>
#include <format>
#include <ranges>
#include <set>

namespace Generator {

bool PumlGenerator::isClass(const Model::Project& project, const std::string& name) {
    return std::ranges::any_of(project.classes, [&](const auto& cls) { return cls.name == name; });
}

bool PumlGenerator::isUseCase(const Model::Project& project, const std::string& name) {
    return std::ranges::any_of(project.useCases, [&](const auto& uc) { return uc.name == name; });
}

std::string PumlGenerator::generateDesignModel(const Model::Project& project) {
    if (!std::ranges::any_of(project.classes, [](const auto& cls) { return cls.isDesign; })) return "";

    std::stringstream ss;
    ss << "@startuml\n";
    ss << "' PlantUML generated by MODT\n";
    ss << std::format("title Design Model: {}\n", project.title.empty() ? project.name : project.title);
    for (const auto& header : project.pumlHeaders) {
        ss << header << "\n";
    }

    for (const auto& cls : project.classes) {
        if (!cls.isDesign) continue;

        if (isActor(cls)) {
            ss << std::format("actor {}", cls.name);
        } else {
            ss << std::format("class {}", cls.name);
        }

        if (!cls.stereotypes.empty()) {
            ss << " <<";
            for (size_t i = 0; i < cls.stereotypes.size(); ++i) {
                ss << translateStereotype(cls.stereotypes[i]);
                if (i < cls.stereotypes.size() - 1) ss << ", ";
            }
            ss << ">>";
        }
        ss << " {\n";

        for (const auto& attr : cls.attributes) {
            if (!attr.isDesign) continue;
            ss << std::format("  {}{}{}", attr.visibility, (attr.visibility.empty() ? "" : " "), attr.name);
            if (!attr.type.empty()) ss << std::format(" : {}", attr.type);
            ss << "\n";
        }

        for (const auto& method : cls.methods) {
            if (!method.isDesign) continue;
            std::string sig = method.name + "(";
            for (size_t i = 0; i < method.parameters.size(); ++i) {
                sig += method.parameters[i].name;
                if (!method.parameters[i].type.empty()) sig += ": " + method.parameters[i].type;
                if (i < method.parameters.size() - 1) sig += ", ";
            }
            sig += ")";
            ss << std::format("  {}{}{}\n", method.visibility, (method.visibility.empty() ? "" : " "), sig);
        }
        ss << "}\n";

        if (!cls.baseClass.empty()) {
            ss << std::format("{} <|-- {}\n", cls.baseClass, cls.name);
        }
    }

    for (const auto& en : project.enums) {
        if (!en.isDesign) continue;
        ss << std::format("enum {} {{\n", en.name);
        for (const auto& v : en.values) {
            ss << std::format("  {}\n", v);
        }
        ss << "}\n";
    }

    for (const auto& rel : project.relationships) {
        if (isClass(project, rel.from) && isClass(project, rel.to)) {
            ss << std::format("{} {} {} {} {}", 
                rel.from, 
                (rel.fromLabel.empty() ? "" : std::format("\"{}\"", rel.fromLabel)),
                rel.type,
                (rel.toLabel.empty() ? "" : std::format("\"{}\"", rel.toLabel)),
                rel.to);
            if (!rel.label.empty()) ss << std::format(" : {}", rel.label);
            ss << "\n";
        }
    }

    ss << "@enduml\n";
    return ss.str();
}

std::string PumlGenerator::generateDomainModel(const Model::Project& project) {
    if (!std::ranges::any_of(project.classes, [](const auto& cls) { return cls.isAnalysis; })) return "";

    std::stringstream ss;
    ss << "@startuml\n";
    ss << "' PlantUML generated by MODT\n";
    ss << std::format("title Domain Model: {}\n", project.title.empty() ? project.name : project.title);
    for (const auto& header : project.pumlHeaders) {
        ss << header << "\n";
    }

    for (const auto& cls : project.classes) {
        if (!cls.isAnalysis) continue;

        if (isActor(cls)) {
            ss << std::format("actor {} {{\n", cls.name);
        } else {
            ss << std::format("class {} {{\n", cls.name);
        }
        for (const auto& attr : cls.attributes) {
            if (!attr.isAnalysis) continue;
            ss << std::format("  {}", attr.name);
            if (!attr.type.empty()) ss << std::format(" : {}", attr.type);
            ss << "\n";
        }
        for (const auto& method : cls.methods) {
            if (!method.isAnalysis) continue;
            std::string sig = method.name + "(";
            for (size_t i = 0; i < method.parameters.size(); ++i) {
                sig += method.parameters[i].name;
                if (!method.parameters[i].type.empty()) sig += ": " + method.parameters[i].type;
                if (i < method.parameters.size() - 1) sig += ", ";
            }
            sig += ")\n";
            ss << "  " << sig;
        }
        ss << "}\n";

        if (!cls.baseClass.empty()) {
            ss << std::format("{} <|-- {}\n", cls.baseClass, cls.name);
        }
    }

    for (const auto& en : project.enums) {
        if (!en.isAnalysis) continue;
        ss << std::format("enum {} {{\n", en.name);
        for (const auto& v : en.values) {
            ss << std::format("  {}\n", v);
        }
        ss << "}\n";
    }

    for (const auto& rel : project.relationships) {
        if (isClass(project, rel.from) && isClass(project, rel.to)) {
            ss << rel.from << (rel.fromLabel.empty() ? "" : " \"" + rel.fromLabel + "\"") 
               << " " << rel.type << " " 
               << (rel.toLabel.empty() ? "" : "\"" + rel.toLabel + "\" ") << rel.to;
            if (!rel.label.empty()) ss << " : " << rel.label;
            ss << std::endl;
        }
    }

    ss << "@enduml" << std::endl;
    return ss.str();
}

std::string PumlGenerator::generateActivityDiagram(const Model::Project& project) {
    if (project.useCases.empty()) return "";

    auto sanitize = [](std::string s) {
        std::replace(s.begin(), s.end(), ' ', '_');
        std::replace(s.begin(), s.end(), '-', '_');
        std::replace(s.begin(), s.end(), '.', '_');
        return s;
    };

    std::stringstream ss;
    ss << "@startuml\n";
    ss << "' PlantUML generated by MODT\n";
    ss << "skinparam MessageAlign center\n";
    ss << std::format("title Activity Diagram: {}\n", project.title.empty() ? project.name : project.title);
    for (const auto& header : project.pumlHeaders) {
        ss << header << "\n";
    }

    ss << "start\n";
    if (project.useCases.size() > 1) ss << "split\n";

    for (size_t i = 0; i < project.useCases.size(); ++i) {
        const auto& uc = project.useCases[i];
        
        // Use Actor partition for the entire use case if actor is present
        if (!uc.actor.empty()) {
            ss << std::format("partition \"{}\" {{\n", uc.actor);
        } else {
            ss << std::format("partition \"{}\" {{\n", uc.name);
        }
        
        // Label detection: collect explicit labels and step names that are targets
        std::map<std::string, size_t> labelPositions;
        for (size_t j = 0; j < uc.actions.size(); ++j) {
            if (!uc.actions[j].label.empty()) {
                labelPositions[uc.actions[j].label] = j;
            }
        }
        
        // Also allow jumping to step names (simplified)
        for (size_t j = 0; j < uc.actions.size(); ++j) {
            if (!uc.actions[j].name.empty() && !labelPositions.contains(uc.actions[j].name)) {
                labelPositions[uc.actions[j].name] = j;
            }
        }

        std::string loopStartLabel = "";
        for (size_t j = 0; j < uc.actions.size(); ++j) {
            if (!uc.actions[j].gotoLabel.empty()) {
                std::string target = uc.actions[j].gotoLabel;
                if (target != "end" && labelPositions.contains(target) && labelPositions[target] <= j) {
                    if (loopStartLabel.empty()) loopStartLabel = target;
                }
            }
        }

        std::string currentAltCond = "";
        bool inAlt = false;
        bool altBlockHasLoopBack = false;
        bool hasFinishedIf = false;

        for (size_t j = 0; j < uc.actions.size(); ++j) {
            const auto& action = uc.actions[j];
            
            if (!loopStartLabel.empty() && (action.label == loopStartLabel || action.name == loopStartLabel)) {
                ss << "    repeat\n";
            }

            // Check if this step is a target for any jump
            bool isTarget = false;
            for (const auto& a : uc.actions) {
                if (a.gotoLabel == action.label && !action.label.empty()) isTarget = true;
                if (a.gotoLabel == action.name) isTarget = true;
            }

            if (!action.label.empty()) {
                ss << std::format("    label {}_{}\n", sanitize(uc.name), sanitize(action.label));
            } else if (isTarget) {
                ss << std::format("    label {}_{}\n", sanitize(uc.name), sanitize(action.name));
            }

            if (action.isAlternative) {
                if (!inAlt) {
                    ss << "    if (" << (action.condition.empty() ? "alternative" : action.condition) << ") then (yes)\n";
                    inAlt = true;
                    currentAltCond = action.condition;
                    altBlockHasLoopBack = false;
                } else if (!action.condition.empty() && action.condition != currentAltCond) {
                    ss << "    elseif (" << action.condition << ") then (yes)\n";
                    currentAltCond = action.condition;
                }

                if (!action.gotoLabel.empty()) {
                    if (!loopStartLabel.empty() && action.gotoLabel == loopStartLabel) {
                        altBlockHasLoopBack = true;
                        ss << "      repeat while ()\n";
                    } else if (action.gotoLabel == "end") {
                        ss << "      stop\n";
                    } else {
                        ss << std::format("      goto {}_{}\n", sanitize(uc.name), sanitize(action.gotoLabel));
                    }
                } else {
                    ss << std::format("      :{};\n", action.name.empty() || action.name == ":" || action.name == " " ? "skip" : action.name);
                }
            } else {
                if (inAlt) {
                    ss << "    else (no)\n    endif\n";
                    inAlt = false;
                    currentAltCond = "";
                    altBlockHasLoopBack = false;
                }

                if (!action.gotoLabel.empty()) {
                    if (!loopStartLabel.empty() && action.gotoLabel == loopStartLabel) {
                        ss << "    repeat while ()\n";
                    } else if (action.gotoLabel == "end") {
                        ss << "    stop\n";
                    } else {
                        ss << std::format("    goto {}_{}\n", sanitize(uc.name), sanitize(action.gotoLabel));
                    }
                } else {
                    ss << std::format("    :{};\n", action.name.empty() || action.name == ":" || action.name == " " ? "skip" : action.name);
                }
            }
        }
        
        if (inAlt) {
            if (altBlockHasLoopBack) {
                ss << "    else (no)\n      break\n    endif\n";
                ss << "    repeat while ()\n";
            } else {
                ss << "    else (no)\n    endif\n";
            }
        }

        ss << std::format("    label {}_{}\n", sanitize(uc.name), "end");
        ss << "}\n";
        if (i < project.useCases.size() - 1) ss << "split again\n";
    }

    if (project.useCases.size() > 1) ss << "endsplit\n";
    ss << "stop\n";
    ss << "@enduml\n";
    return ss.str();
}

std::map<std::string, std::string> PumlGenerator::generateSystemSequenceDiagrams(const Model::Project& project) {
    std::map<std::string, std::string> diagrams;
    if (project.useCases.empty()) return diagrams;

    for (const auto& uc : project.useCases) {
        std::stringstream ss;
        ss << "@startuml\n";
        ss << std::format("title Sequence Diagram: {}\n", uc.name);
        for (const auto& header : project.pumlHeaders) {
            ss << header << "\n";
        }
        
        std::string actor = uc.actor.empty() ? "User" : translateStereotype(uc.actor);
        std::string actorAlias = "Actor";
        ss << std::format("actor \"{}\" as {}\n", actor, actorAlias);
        ss << "participant \"system\" as System\n";

        // Collect all mentioned participants for dynamic registration
        std::set<std::string> participants;
        participants.insert("System");

        auto getAlias = [](const std::string& name) {
            std::string alias = name;
            if (alias.empty()) return std::string("Unknown");
            if (alias[0] == '@') alias = alias.substr(1);
            std::replace(alias.begin(), alias.end(), ' ', '_');
            return alias;
        };

        auto resolveTarget = [&](const std::string& target) {
            if (target == "@sys") return std::string("System");
            if (target == "@user" || target == "@actor" || target == "@me") return actorAlias;
            return getAlias(target);
        };

        for (const auto& action : uc.actions) {
            if (action.target.empty() || action.target == "@sys" || action.target == "@user" || action.target == "@actor" || action.target == "@me") continue;
            std::string tAlias = getAlias(action.target);
            if (!participants.contains(tAlias) && tAlias != actorAlias) {
                ss << std::format("participant \"{}\" as {}\n", translateStereotype(action.target), tAlias);
                participants.insert(tAlias);
            }
        }

        ss << "\n";
        bool inAlt = false;
        std::string currentAltCond = "";

        for (const auto& action : uc.actions) {
            std::string nl = action.name; std::ranges::transform(nl, nl.begin(), ::tolower);
            bool isResp = (!action.target.empty() && (action.target == "@user" || action.target == "@actor" || action.target == "@me")) ||
                          ((action.target.empty() || action.target == "@sys") && 
                           (nl.starts_with("show") || nl.starts_with("display") || nl.starts_with("output") || 
                            nl.find("message") != std::string::npos || nl.find("error") != std::string::npos || nl.find("success") != std::string::npos));

            if (action.isAlternative) {
                std::string cond = action.condition;
                if (!inAlt) {
                    if (cond.empty()) cond = "condition";
                    ss << std::format("alt {}\n", cond);
                    inAlt = true;
                    currentAltCond = cond;
                } else {
                    if (cond.empty()) cond = "alternative";
                    ss << std::format("else {}\n", cond);
                    currentAltCond = cond;
                }
            }

            if (!action.gotoLabel.empty()) continue; 
            if (action.isAlternative && action.name.empty()) continue; 

            // If we have a message and we are NOT alternative, but we were inAlt, check if we should end
            if (!action.isAlternative && inAlt) {
                 // Heuristic: If this is a response or a call, but not an alt, we might be outside.
                 // However, many users put steps inside the branch without braces.
                 // In our Case, "Show Error" follows "alt invalid" and "Success" follows "else valid".
            }

            std::string from = actorAlias, to = "System";
            if (isResp) {
                from = "System"; to = actorAlias;
            } else if (!action.target.empty() && action.target != "@sys") {
                to = resolveTarget(action.target);
                // System usually sends something TO the target, UNLESS it's user-to-system
                from = "System";
            } else if (action.target == "@sys") {
                 // Explicit actor calling system
                 from = actorAlias;
                 to = "System";
            }

            ss << std::format("{} -> {} : {}", from, to, action.name);
            if (!action.parameters.empty()) {
                ss << "(";
                for (size_t j = 0; j < action.parameters.size(); ++j) {
                    ss << action.parameters[j].name << (j < action.parameters.size() - 1 ? ", " : "");
                }
                ss << ")";
            }
            ss << "\n";
        }
        if (inAlt) ss << "end\n";

        ss << "@enduml\n";
        diagrams[uc.name] = ss.str();
    }

    return diagrams;
}

std::map<std::string, std::string> PumlGenerator::generateStateMachineDiagrams(const Model::Project& project) {
    std::map<std::string, std::string> diagrams;
    
    for (const auto& cls : project.classes) {
        bool hasState = std::ranges::any_of(cls.attributes, [](const auto& attr) {
            return attr.metadata.contains("state") || attr.metadata.contains("State");
        });

        if (!hasState) continue;

        std::stringstream ss;
        ss << "@startuml\n";
        ss << std::format("title State Machine: {}\n", cls.name);
        for (const auto& header : project.pumlHeaders) {
            ss << header << "\n";
        }
        
        struct Trans { std::string from, to, trigger; };
        std::vector<Trans> transitions;
        std::set<std::string> allStates;
        std::set<std::string> hasIncoming;
        std::string forcedInitial = "";

        // Check for forced initial state in metadata
        for (const auto& attr : cls.attributes) {
            if (attr.metadata.contains("initial") || attr.metadata.contains("Initial")) {
                std::string val = attr.metadata.contains("initial") ? attr.metadata.at("initial") : attr.metadata.at("Initial");
                if (val == "false" || val == "False") forcedInitial = "Not_" + attr.name;
                else forcedInitial = attr.name;
            }
        }

        for (const auto& uc : project.useCases) {
            std::string fromState = "";
            std::string toState = "";
            
            for (const auto& pre : uc.preconditions) {
                std::string preLower = pre;
                std::ranges::transform(preLower, preLower.begin(), ::tolower);
                std::string clsNameLower = cls.name;
                std::ranges::transform(clsNameLower, clsNameLower.begin(), ::tolower);

                if (preLower.find(clsNameLower + ".") != std::string::npos || preLower.find(clsNameLower + " ") != std::string::npos) {
                    size_t dotPos = preLower.find('.');
                    if (preLower.starts_with("!")) fromState = "Not_" + pre.substr(dotPos + 1);
                    else fromState = pre.substr(dotPos != std::string::npos ? dotPos + 1 : 0);
                }
            }
            for (const auto& post : uc.postconditions) {
                std::string postLower = post;
                std::ranges::transform(postLower, postLower.begin(), ::tolower);
                std::string clsNameLower = cls.name;
                std::ranges::transform(clsNameLower, clsNameLower.begin(), ::tolower);

                if (postLower.find(clsNameLower + ".") != std::string::npos || postLower.find(clsNameLower + " ") != std::string::npos) {
                    size_t dotPos = postLower.find('.');
                    if (postLower.starts_with("!")) toState = "Not_" + post.substr(dotPos + 1);
                    else toState = post.substr(dotPos != std::string::npos ? dotPos + 1 : 0);
                }
            }

            if (!toState.empty()) {
                std::string finalFrom = fromState.empty() ? "Initial" : fromState;
                transitions.push_back({finalFrom, toState, uc.name});
                allStates.insert(finalFrom);
                allStates.insert(toState);
                hasIncoming.insert(toState);
            }
        }

        for (const auto& method : cls.methods) {
            for (const auto& eff : method.effects) {
                std::string trigger = method.name;
                if (!eff.trigger.empty()) trigger += " (" + eff.trigger + ")";

                std::string fromVal = eff.fromValue;
                if (fromVal.empty()) {
                    for (const auto& pre : method.preconditions) {
                        if (pre.find(eff.variable) != std::string::npos) {
                             if (pre.starts_with("!")) fromVal = "Not_" + eff.variable;
                             else fromVal = eff.variable;
                             break;
                        }
                    }
                } else {
                    if (fromVal == "true") fromVal = eff.variable;
                    else if (fromVal == "false") fromVal = "Not_" + eff.variable;
                    else if (fromVal.starts_with("!")) fromVal = "Not_" + fromVal.substr(1);
                }

                auto resolveVal = [&](const std::string& val, const std::string& current) {
                    if (val == "true") return eff.variable;
                    if (val == "false") return std::string("Not_") + eff.variable;
                    if (val.starts_with("!")) {
                        std::string var = val.substr(1);
                        if (var == "State" || var == "state") var = eff.variable;
                        
                        if (var == eff.variable) {
                            if (current == eff.variable) return std::string("Not_") + eff.variable;
                            if (current == "Not_" + eff.variable) return eff.variable;
                            return std::string("Not_") + eff.variable; // Default to Negated if unknown
                        }
                        return std::string("Not_") + var;
                    }
                    return val;
                };

                if (fromVal.empty()) {
                    // If we don't know where it comes from, and it's a toggle, we might want to add BOTH transitions
                    if (eff.value == "!" + eff.variable || eff.value == "!State" || eff.value == "!state") {
                        transitions.push_back({eff.variable, "Not_" + eff.variable, trigger});
                        transitions.push_back({"Not_" + eff.variable, eff.variable, trigger});
                        allStates.insert(eff.variable);
                        allStates.insert("Not_" + eff.variable);
                        hasIncoming.insert(eff.variable);
                        hasIncoming.insert("Not_" + eff.variable);
                        continue;
                    }
                    fromVal = "[*]";
                }

                std::string toVal = resolveVal(eff.value, fromVal);

                transitions.push_back({fromVal, toVal, trigger});
                if (fromVal != "[*]") allStates.insert(fromVal);
                allStates.insert(toVal);
                hasIncoming.insert(toVal);
            }
        }

        // Declare states explicitly
        for (const auto& s : allStates) {
            if (s != "[*]" && s != "Initial") {
                ss << std::format("state {}\n", s);
            }
        }
        ss << "\n";

        if (!forcedInitial.empty()) {
            ss << std::format("[*] --> {}\n", forcedInitial);
        } else {
            for (const auto& s : allStates) {
                if (!hasIncoming.contains(s) || s == "Initial") {
                    if (s != "[*]") {
                        ss << std::format("[*] --> {}\n", s);
                    }
                }
            }
        }

        for (const auto& t : transitions) {
            ss << std::format("{} --> {} : {}\n", t.from, t.to, t.trigger);
        }

        ss << "@enduml\n";
        diagrams[cls.name] = ss.str();
    }

    return diagrams;
}

bool PumlGenerator::isActor(const Model::Class& cls) {
    return std::ranges::any_of(cls.stereotypes, [](const auto& s) {
        std::string slower = s;
        std::ranges::transform(slower, slower.begin(), ::tolower);
        return slower == "actor";
    });
}

std::string PumlGenerator::translateStereotype(const std::string& s) {
    if (s == "@sys") return "system";
    if (s == "@user") return "user";
    if (s == "@ext") return "external";
    if (s == "@db") return "database";
    if (s == "@api") return "api";
    return s;
}

} // namespace Generator
