/*
 * MODT (Modeling Tool)
 * Copyright (C) 2026 Eduard Fekete <modt@eduardfekete.com>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

#include "SqlGenerator.hpp"
#include <sstream>
#include <algorithm>
#include <format>
#include <ranges>
#include <vector>
#include <set>

namespace Generator {

bool isManyToMany(const Model::Relationship& rel) {
    auto m = [](const std::string& l) {
        if (l.empty()) return false;
        return l.find('*') != std::string::npos || (l.size() == 1 && l[0] > '1' && l[0] <= '9') || (l.size() > 1 && l.find("..") == std::string::npos && std::isdigit(l[0]));
    };
    return m(rel.fromLabel) && m(rel.toLabel);
}

bool isMany(const std::string& label) {
    if (label.empty()) return false;
    if (label.find('*') != std::string::npos) return true;
    for (char c : label) if (std::isdigit(c) && c > '1') return true;
    if (label.find("..") != std::string::npos) {
        std::string last = label.substr(label.find_last_of('.') + 1);
        if (last == "*") return true;
        try { if (std::stoi(last) > 1) return true; } catch (...) {}
    }
    return false;
}

std::string SqlGenerator::generate(const Model::Project& project) {
    if (!std::ranges::any_of(project.classes, [](const auto& cls) { return cls.isDesign; })) return "";

    std::stringstream ss;
    ss << "-- SQL Schema generated by MODT\n\n";

    // 0. Enums
    for (const auto& en : project.enums) {
        if (!en.isDesign) continue;
        ss << std::format("CREATE TYPE {} AS ENUM (", en.name);
        for (size_t i = 0; i < en.values.size(); ++i) {
            ss << std::format("'{}'", en.values[i]);
            if (i < en.values.size() - 1) ss << ", ";
        }
        ss << ");\n\n";
    }

    // 1. Tables
    for (const auto& cls : project.classes) {
        if (!cls.isDesign) continue;

        ss << std::format("CREATE TABLE {} (\n", cls.name);
        
        std::vector<std::string> columns;
        std::vector<std::string> constraints;
        std::set<std::string> addedFKs;

        bool hasExplicitId = std::ranges::any_of(cls.attributes, [](const auto& attr) {
            return attr.name == "id" && attr.isDesign;
        });

        if (!hasExplicitId) {
            columns.push_back("    id INT PRIMARY KEY AUTO_INCREMENT");
        }

        // Inheritance
        if (!cls.baseClass.empty()) {
            std::string fkCol = "parent";
            columns.push_back(std::format("    {} INT", fkCol));
            constraints.push_back(std::format("    FOREIGN KEY ({}) REFERENCES {}(id)", fkCol, cls.baseClass));
            addedFKs.insert(fkCol);
        }

        for (const auto& attr : cls.attributes) {
            if (!attr.isDesign) continue;
            std::string col = std::format("    {} ", attr.name);
            if (attr.metadata.contains("db")) {
                col += attr.metadata.at("db");
            } else {
                std::string type = attr.type;
                std::ranges::transform(type, type.begin(), ::tolower);
                if (type == "string" || type.empty()) col += "VARCHAR(255)";
                else if (type == "int") col += "INT";
                else if (type == "bool") col += "BOOLEAN";
                else col += type;
            }
            columns.push_back(col);
        }

        // Relationships (FKs for 1:N)
        for (const auto& rel : project.relationships) {
            auto isCls = [&](const std::string& name) {
                return std::ranges::any_of(project.classes, [&](const auto& c) { return c.name == name; });
            };
            if (!isCls(rel.from) || !isCls(rel.to)) continue;

            std::string targetTable = "";
            bool iAmMany = false;

            if (rel.to == cls.name && !isMany(rel.fromLabel) && isMany(rel.toLabel)) {
                targetTable = rel.from;
                iAmMany = true;
            } else if (rel.from == cls.name && isMany(rel.fromLabel) && !isMany(rel.toLabel)) {
                targetTable = rel.to;
                iAmMany = true;
            }

            if (iAmMany) {
                std::string colName = rel.label.empty() ? targetTable + "_id" : rel.label;
                std::replace(colName.begin(), colName.end(), ' ', '_');

                if (!addedFKs.contains(colName)) {
                    columns.push_back(std::format("    {} INT", colName));
                    constraints.push_back(std::format("    FOREIGN KEY ({}) REFERENCES {}(id)", colName, targetTable));
                    addedFKs.insert(colName);
                }
            }
        }

        for (size_t i = 0; i < columns.size(); ++i) {
            ss << columns[i] << (i < columns.size() - 1 || !constraints.empty() ? "," : "") << "\n";
        }
        for (size_t i = 0; i < constraints.size(); ++i) {
            ss << constraints[i] << (i < constraints.size() - 1 ? "," : "") << "\n";
        }
        ss << ");\n\n";
    }

    // 2. Junction Tables
    for (const auto& rel : project.relationships) {
        if (isManyToMany(rel)) {
            auto isCls = [&](const std::string& name) {
                return std::ranges::any_of(project.classes, [&](const auto& c) { return c.name == name; });
            };
            if (!isCls(rel.from) || !isCls(rel.to)) continue;

            std::string tableName = rel.from;
            if (!rel.label.empty()) tableName += "_" + rel.label;
            tableName += "_" + rel.to;
            std::replace(tableName.begin(), tableName.end(), ' ', '_');

            ss << std::format("CREATE TABLE {} (\n", tableName);
            ss << std::format("    {}_id INT,\n", rel.from);
            ss << std::format("    {}_id INT,\n", rel.to);
            ss << std::format("    PRIMARY KEY ({}_id, {}_id),\n", rel.from, rel.to);
            ss << std::format("    FOREIGN KEY ({}_id) REFERENCES {}(id),\n", rel.from, rel.from);
            ss << std::format("    FOREIGN KEY ({}_id) REFERENCES {}(id)\n", rel.to, rel.to);
            ss << ");\n\n";
        }
    }

    return ss.str();
}

} // namespace Generator


